version: 2
mergeable:
  - when: pull_request.opened, pull_request.synchronize # can be one or more
    validate:
      - do: label
        must_exclude:
          regex: 'status: i18n check required'
          message: 'A member of translation team needs to review this PR'
        must_include:
          regex 'ready to go'
          message: 'Please add ready to go label so PR can be merged.'
#      - do: approvals
#        min:
#          count: 1
#          message: 'At least two approvals must be given.'
#        required:
#          reviewers: [ randelldawson, ojeytonwilliams ] # list of github usernames required to review         
