version: 2
mergeable:
  - when: pull_request.opened, pull_request.synchronize, pull_request.labeled, pull_request.unlabeled
    validate:
      - do: label
        must_exclude:
          regex: 'status: i18n check required|status: needs an english review'
          message: Must not need any reviews          
      - do: approvals
        min:
          count: 1
          message: 'At least two approvals must be given.'
        required:
          reviewers: [ randelldawson, ojeytonwilliams, krherrmann ] # list of github usernames required to review         
