version: 2
mergeable:
  - when: pull_request.opened, pull_request.synchronize, pull_request.labeled, pull_request.unlabeled
    validate:
      - do: label
        must_include:
          regex: 'status: initial review(s) complete'
          message: `initial review complete` label must be present or PR is not mergeable.
        must_exclude:
          regex: 'status: i18n check required'
          message: When `status: i18n check required` is present, PR is not mergeable.
      - do: approvals
        min:
          count: 1
          message: 'At least one approval must be given.'
        or:
          - required:
            reviewers: [ krherrmann ]
          - required:
            reviewers: [ ojeytonwilliams ]
    fail:
      - do: checks
        status: failure
        payload:
          title: 'Mergeable Run has completed with failures!'
          summary: "### Status: {{toUpperCase validationStatus}}\n
                     Here are some stats of the run:\n
                     {{validationCount}} validations were ran.\n
                     {{passCount}} PASSED\n
                     {{failCount}} FAILED"
          text: "{{#each validationSuites}}
            #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
            {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n{{/each}}
            {{/each}}"
