version: 2
mergeable:
  - when: pull_request.opened, pull_request.synchronize, pull_request.labeled, pull_request.unlabeled
    validate:
      - do: label
        must_include:
          regex: 'status: initial review\(s\) complete'
          message: 'The `initial review complete` label must be present or PR is not mergeable.'
        must_exclude:
          regex: 'status: i18n check required'
          message: 'When the `status: i18n check required` is present, PR is not mergeable.'
      - do: approvals
        min:
          count: 1
          message: 'At least one approval must be given or PR is not mergeable.'
