version: 2
mergeable:
  - when: pull_request.opened, pull_request.synchronize, pull_request.labeled, pull_request.unlabeled
    validate:
      - do: label
        must_exclude:
          regex: 'status: i18n check required|status: needs an english review'
          message: Must not need any reviews
      - do: approvals
        min:
          count: 1
          message: 'At least one approval must be given.'
        required:
          reviewers: [ krherrmann ] # list of github usernames required to review
      - do: checks
        status: 'failure' # Can be: success, failure, neutral, cancelled, timed_out, or action_required
        payload:
          title: 'Mergeable Run have been Completed!'
          summary: "All the validators have returned 'pass'! \n Here are some stats of the run: \n {{validationCount}} validations were ran"
