version: 2
mergeable:
  - when: pull_request.opened, pull_request.synchronize, pull_request.labeled, pull_request.unlabeled
    validate:
      - do: label
        must_exclude:
          regex: 'status: i18n check required|status: needs an english review'
          message: Must not need any reviews
      - do: approvals
        min:
          count: 1
          message: 'At least one approval must be given.'
        or:
          - required:
            reviewers: [ krherrmann ]
          - required:
            reviewers: [ ojeytonwilliams ]
    fail:
      - do: checks
        status: 'fail' # Can be: success, failure, neutral, cancelled, timed_out, or action_required
        payload:
          title: 'Mergeable Run has completed!'
          summary: "### Status: {{toUpperCase validationStatus}}
                     Here are some stats of the run:
                     {{validationCount}} validations were ran.
                     {{passCount}} PASSED
                     {{failCount}} FAILED"
          text: "{{#each validationSuites}}
                  #### {{{statusIcon status}}} Validator: {{toUpperCase name}}
                  {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}*** {{/each}}
                {{/each}}"
