version: 2
mergeable:
  - when: pull_request.opened, pull_request.synchronize, pull_request.labeled, pull_request.unlabeled
    validate:
      - do: label
        must_include:
          regex: 'status: initial review\(s\) complete'
          message: 'The `initial review complete` label must be present or PR is not mergeable.'
        must_exclude:
          regex: 'status: i18n check required'
          message: 'When the `status: i18n check required` is present, PR is not mergeable.'
      - do: approvals
        min:
          count: 1
          message: 'At least one approval must be given or PR is not mergeable.'
    fail:
      - do: checks
        status: failure
        payload:
          title: 'Mergeable Run has completed with failures2!'
          summary: |
            ### Status: {{toUpperCase validationStatus}}
            Here are some stats of the run:
            {{validationCount}} validations were ran.
            {{passCount}} PASSED
            {{failCount}} FAILED"
          text: "{{#each validationSuites}}
            #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
            {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n{{/each}}
            {{/each}}"
