version: 2
mergeable:
  - when: pull_request.opened, pull_request.synchronize
    validate:
      - do: label
        must_exclude:
          regex: 'status: i18n check required'
          message: This is work in progress. Do not merge yet.
        must_include:
          regex: ready to go
          message: Please add ready to go label so PR can be merged          
#      - do: approvals
#        min:
#          count: 1
#          message: 'At least two approvals must be given.'
#        required:
#          reviewers: [ randelldawson, ojeytonwilliams ] # list of github usernames required to review         
