name: 'Crowdin Updater'
description: 'Upates Crowdin files in the curriculum project for a merged PR'
inputs:
  pr-num:
    description: 'The number of the pull request'
    default: ${{ github.event.pull_request.number }}
  github-token:
    description: 'GitHub personal access token'
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'