name: 'Crowdin Updater'
description: 'Upates Crowdin files in the curriculum project for a merged PR'
inputs:
  commit-sha:
    description: 'The commit number pushed'
    required: true

  github-token:
    description: 'GitHub personal access token'
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'