name: Verify if i18n review is required
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]

jobs:
  labelChecker:
    runs-on: ubuntu-latest
    steps:
    - name: Fail if i18n review required
      if: "contains(github.event.pull_request.labels.*.name, 'status: i18n review required')"
      run: |
        exit 1
    - name: No i18n review required
      if: success()
      run: |
        exit 0
