name: Verify if any failure labels appear on PR
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]

jobs:
  labelChecker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
        uses: actions/checkout@v2
    - name: Check for failure labels
      uses: ./github/actions/labels-to-fail/index.js
      with:
        labels-to-fail: ['status: blocked', 'status: i18n review required']