name: Update Crowdin files
on:
  push:
    branches:
      - master

jobs:
  updateCrowdin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update Crowdin based on pushed commit
      uses: ./.github/actions/crowdin-updater