name: Label
on:
  pull_request:
    types: [openend, reopened, synchronize, labeled, unlabeled]

jobs:
  labelChecker:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on the PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: 'Hey go do your thing!'